### ISSUE TITLE
Getting error in Unity 5.6

### ISSUE THREAD

**Issue by Venryx** [SaladLab/Unity3D.IncrementalCompiler#23]
Here is the error:
```
Could not start compilationMissingMethodException: Method not found: 'UnityEditor.Scripting.Compilers.MonoScriptCompilerBase.GetProfileDirectory'.
UnityEditor.Scripting.Compilers.ScriptCompilerBase.BeginCompiling () (at C:/buildslave/unity/build/Editor/Mono/Scripting/Compilers/ScriptCompilerBase.cs:40)
```

As well as:
```
Compilation failed because the compiler couldn't be executed!
```

**Comment by SonicZentropy** [comment]
I'm also getting the same.  I tried to look into it myself but didn't get very far.  I can verify that alexzzzz's non-incremental still works fine with Unity 5.6, so the problem's stemming from something in the incremental-specific code rather than Unity balking at the compiler replacement in general

**Comment by gthx** [comment]
alexzzzz has fixed it for 5.6: https://bitbucket.org/alexzzzz/unity-c-5.0-and-6.0-integration/src/d663da979c4b4690a2094cf18742a4fb81e68e73/CSharp%20vNext%20Support%20Solution/CSharpVNextSupport/CustomCSharpCompiler.cs?at=default&fileviewer=file-view-default#CustomCSharpCompiler.cs-103

**Comment by SonicZentropy** [comment]
Ah that'd explain why his works fine for me and this doesn't!  Should be a pretty easy change to make for this too, thanks

**Comment by veblush** [comment]
Oh you guys already found out! I will make a fix soon!

**Comment by veblush** [comment]
Please check new [release 1.2.9 ](https://github.com/SaladLab/Unity3D.IncrementalCompiler/releases/tag/v1.2.9)

**Comment by SonicZentropy** [comment]
Can confirm it works perfectly in 5.6b9 if you want to close this issue.  Thanks so much!  Unity without this  is so painful
